version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass "" # 비밀번호 없이 쓸 경우
    # command: redis-server --requirepass "my_password" # 비밀번호 설정 시

  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lig3143774
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
